### ISSUE TITLE
One test depending on the order of elements in a Hash

### ISSUE THREAD

**Issue by AlexDaniel** [tony-o/perl6-koos#2]
See this test:
https://github.com/tony-o/perl6-koos/blob/28deec5103cec65f69f4ed2ba2b396efe1212e7b/t/01-searchable.t#L39

The order can be different every run:
`SELECT "a", "c", "d" FROM "dummy" as self left outer join "world" as w on ( "w"."a" = "self"."a" ) AND ( "w"."l" = ? ) WHERE`
* `( "self"."a" = ? ) AND ( "self"."d" = ? ) AND ( "self"."c" = ? ) AND ( ( "self"."b" = ? ) OR ( "self"."b" = ? ) )`
* `( "self"."d" = ? ) AND ( "self"."a" = ? ) AND ( "self"."c" = ? ) AND ( ( "self"."b" = ? ) OR ( "self"."b" = ? ) )`
* `( "self"."d" = ? ) AND ( "self"."c" = ? ) AND ( "self"."a" = ? ) AND ( ( "self"."b" = ? ) OR ( "self"."b" = ? ) )`
* `( ( "self"."b" = ? ) OR ( "self"."b" = ? ) ) AND ( "self"."d" = ? ) AND ( "self"."c" = ? ) AND ( "self"."a" = ? )`

As a result, most of the time the test file fails.

**Comment by AlexDaniel** [comment]
More info: https://cry.nu/perl6/secure-hashing-for-moarvm/

**Comment by tony-o** [comment]
Thank you @AlexDaniel  - should be fixed with 3a36bfa

**Comment by tony-o** [comment]
This should be fixed with a05775d

**Comment by AlexDaniel** [comment]
Looks fixed to me! I tried running it in a loop and no failures. Thanks!
